#ifndef ENCODINGDETECTOR_GLOBAL_H
#define ENCODINGDETECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENCODINGDETECTOR_LIBRARY)
#  define ENCODINGDETECTOR_EXPORT Q_DECL_EXPORT
#else
#  define ENCODINGDETECTOR_EXPORT Q_DECL_IMPORT
#endif

#endif // ENCODINGDETECTOR_GLOBAL_H
